export const productIntroduction = {
    no001: {
        title: "君の名は",
        subtitle: "",
        img: "/assets/img/kiminonawaJ.jpg",
        author: "新海 誠",
        translator: "",
        illustrator: "",
        publishingHouse: "文庫",
        publicationDay: "2016/06/18",
        ISBN: "9784041026229",
        suitableAge: "全齡適讀",
        price: 240,
        bargain: 204,
        bonus: 6,
        shippingMethod: "全球配送　香港到店<br />國內宅配　國內店取",
        Introduction: "",
        details: "條碼：9784041026229<br>規格：平裝 / 262頁 / 14.8 x 10.6 x 1.6 cm / 普通級 / 單色印刷"
    },
    no002: {
        title: "異世界藥局",
        subtitle: "他擁有前世所累積的現代藥學知識，搭配上在異世界得到的作弊能力「物質創造＆物質消除」。",
        img: "/assets/img/isekai.jpg",
        author: "高山理図（keepout）",
        translator: "張以潤",
        illustrator: "keepout",
        publishingHouse: "東立",
        publicationDay: "2016/10/24",
        ISBN: "9789864820863",
        suitableAge: "全齡適讀",
        price: 240,
        bargain: 204,
        bonus: 6,
        shippingMethod: "全球配送　香港到店<br />國內宅配　國內店取",
        Introduction: "一名年輕的藥學學者，因為過於熱衷研究，導致他還壯志未酬就過勞死。<br />而他張開眼睛之後，竟發現自己轉世成了專為王公貴族診療的宮廷藥師名門德‧麥第奇家之子――法馬。然而，法馬對這個充斥錯誤的療法、調劑法，甚至還橫行著稱不上醫療行為的咒法和巫術的世界絕望至極。「不想想辦法不行啊……至少要為這個世界的人們著想――」<br />他擁有前世所累積的現代藥學知識，搭配上在異世界得到的作弊能力「物質創造＆物質消除」。<br />法馬運用這些知識和能力，面對媽媽的腰痛到女王的絕症等等……各種疑難雜症。<br />接著，他與「認為應將真正有效的藥品提供給每一個人」的奴婢少女珞緹、以及美女家教艾倫等人，開設了「異世界藥局」。而法馬訂下的目標則是──<br />",
        details: "編／譯者：張以潤<br />語言：中文繁體<br />規格：平裝<br />分級：普級<br />開數：32開13*19cm<br /><br />出版地：台灣<br />"
    },
    no003: {
        title: "你的名字",
        subtitle: "未曾相識的兩人，不可解的相遇，讓命運的齒輪開始轉動──",
        img: "/assets/img/kiminonawaC.jpg",
        author: "新海誠",
        translator: "黃涓芳",
        illustrator: "",
        publishingHouse: "台灣角川",
        publicationDay: "2016/12/15",
        ISBN: "9789864734542",
        suitableAge: "全齡適讀",
        price: 260,
        bargain: 205,
        bonus: "5%",
        shippingMethod: "全球配送　香港到店<br />國內宅配　國內店取",
        Introduction: "未曾相識的兩人，<br>不可解的相遇，<br>讓命運的齒輪開始轉動──<br><br>家住深山的女高中生三葉，每天過著鬱鬱寡歡的生活。<br>身為鎮長的父親參與的選舉、家中神社的古老習俗、狹小的村莊──在莫名在意四周眼光的年紀，她對都會生活懷抱強烈憧憬。<br>「下輩子，請讓我生為東京的帥哥！」<br>某日，三葉夢見自己變成男高中生。<br>不曾看過的房間、不認識的朋友、繁華的街道與時髦的咖啡廳──三葉在夢裡盡情享受了渴望的都市生活。<br>住在東京的男高中生──瀧，也做了奇怪的夢。在夢裡，他是家住深山的女高中生。<br>偶有遺落的記憶與時間，不可思議卻不斷持續的夢境……三葉和瀧終於察覺：<br>「我和他（她）互換靈魂了嗎？」",
        details: "ISBN：9789864734542<br>叢書系列：輕．文學<br>規格：平裝 / 256頁 / 14.7 x 21 x 1.28 cm / 普通級 / 單色印刷 / 初版<br>出版地：台灣"
    }
}